apiVersion: 1

datasources:
  - name: Cassandra
    uid: Cassandra
    type: hadesarchitect-cassandra-datasource
    access: proxy
    url: cassandra:9042
    isDefault: true
    editable: true
    jsonData:
      keyspace: microservice_metrics
      consistency: ONE
