{
 "title": "Метрики микросервисов",
 "tags": [
  "kafka",
  "spark",
  "hdfs",
  "cassandra"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Интенсивность запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "target": "SELECT service, requests_per_second, window_start FROM microservice_metrics.service_metrics ALLOW FILTERING;",
     "alias": "{{service}}"
    }
   ]
  },
  {
   "title": "Среднее время ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "SELECT service, avg_latency_ms, window_start FROM microservice_metrics.service_metrics ALLOW FILTERING;",
     "alias": "{{service}}"
    }
   ]
  },
  {
   "title": "Количество ошибок",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "SELECT service, error_count, window_start FROM microservice_metrics.service_metrics ALLOW FILTERING;",
     "alias": "{{service}}"
    }
   ]
  }
 ]
}